# Generated by Django 2.1.3 on 2018-11-08 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
        migrations.AddField(
            model_name='project',
            name='short_desc',
            field=models.TextField(default='#', max_length=30),
        ),
    ]
