# Generated by Django 2.1.3 on 2018-11-20 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0002_auto_20181107_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='short_desc',
            field=models.TextField(default='#', max_length=45),
        ),
    ]
