# Generated by Django 2.1.3 on 2018-12-30 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0003_auto_20181120_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image_url',
            field=models.URLField(default='#'),
        ),
    ]
